Validation phase: False
Namespace(ips=999999, bs=4, nodw=10, ntibp=10, sd='UNet', ptd='./vein_sclera_data', is_test_run=True, pruning_phase=False, pbop=False, e_ix=3, mti=2, map=1000000000.0, nept=1, pnkao=20, nftp=1, rn='flops_num', ptp=0.01, tp=False, ifn=(0.5, 0.5, 0.5))
path to file: ./vein_sclera_data
summary for train
valid images: 89
summary for val
valid images: 27
summary for test
valid images: 12
train dataset len: 30
val dataset len: 27
test dataset len: 12
train dataloader num of batches: 8
val dataloader num of batches: 7
test dataloader num of batches: 3
Device: cuda
Traceback (most recent call last):
  File "/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/main.py", line 978, in <module>
    model_wrapper.initialize_pruning(get_importance_dict, unet_input_slice_connection_fn, unet_kernel_connection_fn, FLOPS_min_res_percents, weights_min_res_percents)
TypeError: ModelWrapper.initialize_pruning() takes 5 positional arguments but 6 were given
