Validation phase: True
Namespace(ips=999999, bs=4, nodw=10, ntibp=2, sd='SegNet', ptd='./vein_sclera_data', is_test_run=True, pruning_phase=True, pbop=True, e_ix=3, mti=1000000000.0, map=2, nept=1, pnkao=50, nftp=1, rn='flops_num', ptp=0.05, tp=True)
path to file: ./vein_sclera_data
summary for train
valid images: 89
summary for val
valid images: 27
summary for test
valid images: 12
train dataset len: 30
val dataset len: 27
test dataset len: 12
train dataloader num of batches: 8
val dataloader num of batches: 7
test dataloader num of batches: 3
Device: cuda
loss: 0.340641  [    4/   30]
loss: 0.335284  [    8/   30]
loss: 0.334998  [   12/   30]
loss: 0.335549  [   16/   30]
loss: 0.337021  [   20/   30]
loss: 0.335057  [   24/   30]
loss: 0.337237  [   28/   30]
loss: 0.334132  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.33449812 
 IoU: 0.991653 
 F1: nan 

test Error: 
 Avg loss: 0.33489717 
 IoU: 0.990904 
 F1: nan 

loss: 0.339843  [    4/   30]
loss: 0.333935  [    8/   30]
loss: 0.333988  [   12/   30]
loss: 0.334467  [   16/   30]
loss: 0.339682  [   20/   30]
loss: 0.334326  [   24/   30]
loss: 0.342441  [   28/   30]
loss: 0.331577  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.33411623 
 IoU: 0.991416 
 F1: nan 

test Error: 
 Avg loss: 0.33448017 
 IoU: 0.990904 
 F1: nan 

Goal resource value: 17073125683.2
----------
sortable_list[:5]: [(((0,), 7), 53, 0.02297552116215229), (((0,), 7), 52, 0.024606041610240936), (((0,), 5), 45, 0.02538086101412773), (((0,), 5), 33, 0.02617892622947693), (((0,), 12), 0, 0.026343872770667076)]
disallowed_directly: {((0,), 44), ((0,), 53), ((0,), 56), ((0,), 7), ((0,), 10), ((0,), 19), ((0,), 28), ((0,), 34), ((0,), 37), ((0,), 46), ((0,), 0), ((0,), 58), ((0,), 12), ((0,), 21), ((0,), 24), ((0,), 30), ((0,), 39), ((0,), 48), ((0,), 51), ((0,), 2), ((0,), 5), ((0,), 14), ((0,), 17), ((0,), 26), ((0,), 32), ((0,), 41)}
disallowed_tree_ixs: {((0,), 44), ((0,), 53), ((0,), 56), ((0,), 7), ((0,), 10), ((0,), 19), ((0,), 28), ((0,), 34), ((0,), 37), ((0,), 46), ((0,), 0), ((0,), 58), ((0,), 12), ((0,), 21), ((0,), 24), ((0,), 30), ((0,), 39), ((0,), 48), ((0,), 51), ((0,), 2), ((0,), 5), ((0,), 14), ((0,), 17), ((0,), 26), ((0,), 32), ((0,), 41)}
No more to prune!!!
Current resource value: 19075696128
Copied SegNet_29_94.pth to ./SegNet/safety_copies/actual_safety_copies
File SegNet_0_0_special_save.pth already exists in safety copies, skipping.
File SegNet_7_33.pth already exists in safety copies, skipping.
File SegNet_7_34.pth already exists in safety copies, skipping.
There are no more kernels that could be pruned in the future.
