Validation phase: False
Namespace(iter_possible_stop=999999, BATCH_SIZE=4, NUM_OF_DATALOADER_WORKERS=10, NUM_TRAIN_ITERS_BETWEEN_PRUNINGS=1, SAVE_DIR='SegNet', PATH_TO_DATA='./vein_sclera_data', is_test_run=True, pruning_phase=False, pbop=False, e_ix=3, mti=2, map=1000000000.0, nept=1, pnkao=20, nftp=1, rn='flops_num', ptp=0.01)
path to file: ./vein_sclera_data
summary for train
valid images: 89
summary for val
valid images: 27
summary for test
valid images: 12
train dataset len: 30
val dataset len: 27
test dataset len: 12
train dataloader num of batches: 8
val dataloader num of batches: 7
test dataloader num of batches: 3
Device: cuda
loss: 0.341572  [    4/   30]
loss: 0.339714  [    8/   30]
loss: 0.340637  [   12/   30]
loss: 0.339302  [   16/   30]
loss: 0.335986  [   20/   30]
loss: 0.340985  [   24/   30]
loss: 0.342101  [   28/   30]
loss: 0.342024  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.33473247 
 IoU: 0.991602 
 F1: nan 

test Error: 
 Avg loss: 0.33555218 
 IoU: 0.990904 
 F1: nan 

loss: 0.343186  [    4/   30]
loss: 0.335871  [    8/   30]
loss: 0.337511  [   12/   30]
loss: 0.337657  [   16/   30]
loss: 0.337145  [   20/   30]
loss: 0.336669  [   24/   30]
loss: 0.344093  [   28/   30]
loss: 0.347338  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.33852592 
 IoU: 0.991690 
 F1: nan 

test Error: 
 Avg loss: 0.33928948 
 IoU: 0.990904 
 F1: nan 

