Validation phase: False
Namespace(iter_possible_stop=999999, BATCH_SIZE=4, NUM_OF_DATALOADER_WORKERS=10, NUM_TRAIN_ITERS_BETWEEN_PRUNINGS=1, SAVE_DIR='SegNet', PATH_TO_DATA='./sclera_data', is_test_run=True, pruning_phase=False, pbop=False, e_ix=3, mti=2, map=1000000000.0, nept=1, pnkao=20, nftp=1, rn='flops_num', ptp=0.01)
path to file: ./sclera_data
summary for train
valid images: 1288
summary for val
valid images: 344
summary for test
valid images: 208
train dataset len: 30
val dataset len: 30
test dataset len: 30
train dataloader num of batches: 8
val dataloader num of batches: 8
test dataloader num of batches: 8
Device: cuda
loss: 0.486688  [    4/   30]
loss: 0.513430  [    8/   30]
loss: 0.463830  [   12/   30]
loss: 0.431408  [   16/   30]
loss: 0.504732  [   20/   30]
loss: 0.448068  [   24/   30]
loss: 0.456400  [   28/   30]
loss: 0.447360  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.45438867 
 IoU: 0.868431 
 F1: nan 

test Error: 
 Avg loss: 0.44585872 
 IoU: 0.877141 
 F1: nan 

loss: 0.482910  [    4/   30]
loss: 0.522989  [    8/   30]
loss: 0.470612  [   12/   30]
loss: 0.489006  [   16/   30]
loss: 0.488773  [   20/   30]
loss: 0.494365  [   24/   30]
loss: 0.446986  [   28/   30]
loss: 0.438211  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.45332263 
 IoU: 0.869084 
 F1: nan 

test Error: 
 Avg loss: 0.44897122 
 IoU: 0.873262 
 F1: nan 

