Validation phase: True
Namespace(ips=999999, bs=4, nodw=10, ntibp=2, sd='UNet', ptd='./vein_sclera_data', is_test_run=True, pruning_phase=True, pbop=True, e_ix=3, mti=1000000000.0, map=2, nept=1, pnkao=50, nftp=1, rn='flops_num', ptp=0.05, tp=True, ifn=(0.5, 0.5, 0.5))
path to file: ./vein_sclera_data
summary for train
valid images: 89
summary for val
valid images: 27
summary for test
valid images: 12
train dataset len: 30
val dataset len: 27
test dataset len: 12
train dataloader num of batches: 8
val dataloader num of batches: 7
test dataloader num of batches: 3
Device: cuda
loss: 0.616500  [    4/   30]
loss: 0.609628  [    8/   30]
loss: 0.604770  [   12/   30]
loss: 0.601655  [   16/   30]
loss: 0.597026  [   20/   30]
loss: 0.587345  [   24/   30]
loss: 0.588901  [   28/   30]
loss: 0.583516  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.57280017 
 IoU: 0.991722 
 F1: nan 

test Error: 
 Avg loss: 0.57264471 
 IoU: 0.990904 
 F1: nan 

loss: 0.574548  [    4/   30]
loss: 0.578395  [    8/   30]
loss: 0.568956  [   12/   30]
loss: 0.562042  [   16/   30]
loss: 0.562480  [   20/   30]
loss: 0.552398  [   24/   30]
loss: 0.548883  [   28/   30]
loss: 0.544107  [   16/   30]
validation Error: 
 Avg loss: 0.51687687 
 IoU: 0.991736 
 F1: nan 

test Error: 
 Avg loss: 0.51734414 
 IoU: 0.990904 
 F1: nan 

Goal resource value: 37523835750.4
disallowed_directly: {((((((0,), 2), 0), 1), 0), 0), (((((0,), 8), 1), 0), 3), ((((((0,), 1), 0), 1), 0), 0), ((((((0,), 2), 0), 1), 0), 3), ((((((0,), 1), 0), 1), 0), 3), ((((((0,), 4), 0), 1), 0), 0), (((((0,), 5), 1), 0), 0), ((((((0,), 4), 0), 1), 0), 3), (((((0,), 5), 1), 0), 3), (((((0,), 7), 1), 0), 0), (((((0,), 7), 1), 0), 3), (((0,), 9), 0), (((((0,), 6), 1), 0), 0), (((((0,), 6), 1), 0), 3), ((((((0,), 3), 0), 1), 0), 0), ((((((0,), 3), 0), 1), 0), 3), ((((0,), 0), 0), 3), ((((0,), 0), 0), 0), (((((0,), 8), 1), 0), 0)}
disallowed_tree_ixs: {((((((0,), 2), 0), 1), 0), 0), (((((0,), 8), 1), 0), 3), ((((((0,), 1), 0), 1), 0), 0), ((((((0,), 2), 0), 1), 0), 3), ((((((0,), 1), 0), 1), 0), 3), ((((((0,), 4), 0), 1), 0), 0), (((((0,), 5), 1), 0), 0), ((((((0,), 4), 0), 1), 0), 3), (((((0,), 5), 1), 0), 3), (((((0,), 7), 1), 0), 0), (((((0,), 7), 1), 0), 3), (((0,), 9), 0), (((((0,), 6), 1), 0), 0), (((((0,), 6), 1), 0), 3), ((((((0,), 3), 0), 1), 0), 0), ((((((0,), 3), 0), 1), 0), 3), ((((0,), 0), 0), 3), ((((0,), 0), 0), 0), (((((0,), 8), 1), 0), 0)}
----------
sortable_list[:5]: []
No more to prune!!!
Current resource value: 39523050752
Copied UNet_3_1.pth to ./UNet/safety_copies/actual_safety_copies
File UNet_1_0_just_pruned.pth already exists in safety copies, skipping.
File UNet_0_0_special_save.pth already exists in safety copies, skipping.
Copied UNet_3_2.pth to ./UNet/safety_copies/actual_safety_copies
Copied UNet_2_0_special_save.pth to ./UNet/safety_copies/actual_safety_copies
There are no more kernels that could be pruned in the future.
